# Generated by Django 5.2.8 on 2025-12-14 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='size',
            new_name='file_size',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_own',
            new_name='folder',
        ),
        migrations.RemoveField(
            model_name='file',
            name='encrypted_name',
        ),
        migrations.AddField(
            model_name='file',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='is_encrypted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
